name: Qwerty80
main: me.qwerty80.Qwerty80
version: 1.0
api-version: 1.17
author: sbeve#4701, JusteyCrustey#1293 and LeverClient#1634
depend: ['Multiverse-Core', 'LuckPerms', 'ViaVersion']
commands:
  escape:
    description: Manage and join escape games.
    usage: /escape <list|join>
  lobby:
    description: Go back to the lobby cause ur a chicken
    usage: /lobby
permissions:
  escape.admin:
    description: Use admin permissions.
    default: false